version: "2"
services:
  mudlib:
    image: acmemud/mudlib:1.0
    restart: always
    volumes:
      - /usr/local/acme/mudlib
  driver:
    image: acmemud/driver:3.3
    restart: always
    volumes:
      - /usr/local/acme/
    volumes_from:
      - mudlib
  mud:
    image: acmemud/mud:1.0
    command: /usr/local/acme/bin/ldmud --debug-file /usr/local/acme/mudlib/Debug.log --mudlib /usr/local/acme/mudlib --erq erq
    ports:
      - 2010:2010
    volumes_from:
      - driver
    tty: true
